packages:
  - packages/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.25.1
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
  testing:
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/user-event': ^14.5.2
    '@types/execa': ^2.0.2
    '@types/mock-fs': ^4.13.4
    '@types/supertest': ^6.0.2
    '@vitest/coverage-v8': ^3.1.2
    '@vitest/ui': ^3.1.2
    cross-env: ^7.0.3
    execa: ^9.4.0
    mock-fs: ^5.2.0
    supertest: ^7.0.0
    vitest: ^3.1.2
    vitest-package-exports: ^0.1.1
  types:
    '@types/node': ^22.13.10
  utils:
    dotenv: ^16.4.5
    npm-run-all: ^4.1.5
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
