blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/witsaint/ts-starter/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/witsaint/ts-starter#readme
    about: Check the project documentation
  - name: 🔒 Security Issue
    url: https://github.com/witsaint/ts-starter/security/advisories/new
    about: Report a security vulnerability privately
